---
- name: SNOW Change Request Close by username
  become: false
  hosts: sdwan
  gather_facts: false

  tasks:
  - block:
    - name: Create Service-Now Request
      ansible.builtin.include_role:
        name: "../..//roles/snow_change"
        tasks_from: create_change_task.yml
      vars:
        - sn_start_date: '{{lookup(''pipe'',''date -u +%Y-%m-%d" "%H:%M:00'')}}'
        - sn_end_date: '{{lookup(''pipe'',''date -u -d "+1 hour" +%Y-%m-%d" "%H:%M:00'')}}'

    # Send notificatoin to service-now
    - name: Notify Service-Now details to NetDevOps
      ansible.builtin.include_role:
        name: "../..//roles/notify"
        tasks_from: snow_change_created.yml
      with_items:
       - "{{ migration_webhook }}"
