---

# TEST 1
  - name: TEST 105 LAN - Test reachability and latency to GPR (STH) rotuer in LAN vrf (vManage vpn 10)
    block:
      - cisco.ios.ios_ping:
          dest: 10.61.95.134
          vrf: '10'
        register: ping_sth_gpr_vpn10_a
      - ansible.builtin.set_fact:
          latency_post: "{{ latency_post | combine( { 'sth': ping_sth_gpr_vpn10_a['rtt']['avg'] } ) }}"
    rescue:
      - name: WARNING - Communicstion Error Detected on client vpn10
        ansible.builtin.debug:
          msg: "client test_105 faild"
# Result
  - ansible.builtin.set_fact:
      test_result:
        "{{ test_result + [{ 'severity':'critical', 'description':'Test client vpn10 to STH', 'name':'test_105', 'successful': not ping_sth_gpr_vpn10_a['failed'] }] }}"

# TEST 2
  - name: TEST 110 LAN - Test reachability and latency to GPR (HKG) rotuer in LAN vrf (vManage vpn 10)
    block:
      - cisco.ios.ios_ping:
          dest: 10.200.95.59
          vrf: '10'
        register: ping_hkg_gpr_vpn10_a
      - ansible.builtin.set_fact:
          latency_post: "{{ latency_post | combine( { 'hkg': ping_hkg_gpr_vpn10_a['rtt']['avg'] } ) }}"
    rescue:
      - name: WARNING - Communicstion Error Detected on client vpn10
        ansible.builtin.debug:
          msg: "client test_110 faild"
# Result
  - ansible.builtin.set_fact:
      test_result:
        "{{ test_result + [{ 'severity':'critical', 'description':'Test client vpn10 to HKG', 'name':'test_110', 'successful': not ping_hkg_gpr_vpn10_a['failed'] }] }}"

# TEST 3
  - name: TEST 115 LAN - Test reachability and latency to GPR (SEC) rotuer in LAN vrf (vManage vpn 10)
    block:
      - cisco.ios.ios_ping:
          dest: 10.70.93.46
          vrf: '10'
        register: ping_sec_gpr_vpn10_a
      - ansible.builtin.set_fact:
          latency_post: "{{ latency_post | combine( { 'sec': ping_sec_gpr_vpn10_a['rtt']['avg'] } ) }}"
    rescue:
      - name: WARNING - Communicstion Error Detected on client vpn10
        ansible.builtin.debug:
          msg: "client test_115 faild"
# Result
  - ansible.builtin.set_fact:
      test_result:
        "{{ test_result + [{ 'severity':'critical', 'description':'Test client vpn10 to SEC', 'name':'test_115', 'successful': not ping_sec_gpr_vpn10_a['failed'] }] }}"
