---
- name: Backup IOS Config
  hosts: sdwan
  gather_facts: false
  connection: network_cli

  tasks:
    - name: backup config
      cisco.ios.ios_config:
        backup: true
        backup_options:
          dir_path: "{{ runnconfig_dir }}"
