---
- name: PREUpgrade CISCO IOS to 16.09.07
  hosts: sdwan
  gather_facts: false
  connection: local

  vars:
    upgrade_ios_version: 16.09.07

  tasks:
    # Create Change Request and Task for the operation
    - ansible.builtin.import_tasks: rommon_create_cr.yml

    - ansible.builtin.import_tasks: notify.yml
      vars:
        msg: "IOS upgrade started. Reloadng device."
        hooks:
          - "{{ migration_webhook }}"
          - "{{ operations_webhook }}"

    # Reload Device
    - ansible.builtin.import_tasks: ./tasks/ios_reload.yml
      ignore_errors: true

    # Wait for router to get back from reboot
    - name: reset the connection
      ansible.builtin.meta: reset_connection

    - name: Wait 30 minutes, but only start checking after 180 seconds ( 3 minutes )
      ansible.builtin.wait_for_connection:
        delay: 180
        timeout: 1800
      ignore_errors: true

    # reset connetion again
    - name: reset the connection
      ansible.builtin.meta: reset_connection

    - name: Gather Facts
      cisco.ios.ios_facts:

    - ansible.builtin.import_tasks: rommon_close_cr.yml
      vars:
        sat_code: "successful"
      ignore_errors: true

    - ansible.builtin.import_tasks: notify.yml
      vars:
        color: "00EE00"
        msg: "IOS upgrade to 16.9.7 completed"
        templ: "notify.j2"
        hooks:
          - "{{ migration_webhook }}"
          - "{{ operations_webhook }}"
