name: Code validation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths-ignore:
      - ".github/**"
  workflow_dispatch:

permissions:
  pull-requests: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PIP_EXTRA_INDEX_URL: ${{ secrets.PIP_EXTRA_INDEX_URL }}
      DB_KEY: disabled
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt

      - name: check sorted imports
        run: |
          isort .

      - name: validate with flake8
        run: |
          flake8 . --count --statistics

      - name: Run tests with pytest
        run: |
          pip install .
          pytest
